package f.l.truco.machine;

public enum Event {
    PLAYER_1_PLAY_CARD_1,
    PLAYER_2_PLAY_CARD_1,
    PLAYER_1_PLAY_CARD_2,
    PLAYER_2_PLAY_CARD_2,
    PLAYER_1_PLAY_CARD_3,
    PLAYER_2_PLAY_CARD_3,
    INITIALIZE_TO_PLAYER_1_TURN,
    INITIALIZE_TO_PLAYER_2_TURN,

    INITIALIZE_TEST
}