package f.l.truco.machine;

public enum Event {
    PLAYER_1_PLAY_CARD_1,
    PLAYER_2_PLAY_CARD_1,
    PLAYER_1_PLAY_CARD_2,
    PLAYER_2_PLAY_CARD_2,
    PLAYER_1_PLAY_CARD_3,
    PLAYER_2_PLAY_CARD_3,
    INITIALIZE_TO_PLAYER_1_TURN,
    INITIALIZE_TO_PLAYER_2_TURN,

    PLAYER_1_TRUCO,
    PLAYER_2_TRUCO,
    PLAYER_1_RE_TRUCO,
    PLAYER_2_RE_TRUCO,
    PLAYER_1_VALE_4,
    PLAYER_2_VALE_4,

    PLAYER_1_YES_TRUCO,
    PLAYER_1_NO_TRUCO,
    PLAYER_1_YES_RETRUCO,
    PLAYER_1_NO_RETRUCO,
    PLAYER_1_YES_VALE4,
    PLAYER_1_NO_VALE4,
    PLAYER_2_YES_TRUCO,
    PLAYER_2_NO_TRUCO,
    PLAYER_2_YES_RETRUCO,
    PLAYER_2_NO_RETRUCO,
    PLAYER_2_YES_VALE4,
    PLAYER_2_NO_VALE4,

    INITIALIZE_TEST
}