package f.l.truco.machine;

public enum State {
    INITIAL,
    PLAYER_1_TURN_1,
    PLAYER_2_TURN_1,
    PLAYER_1_TURN_2,
    PLAYER_2_TURN_2,
    PLAYER_1_TURN_3,
    PLAYER_2_TURN_3,
    COMPUTE_1,
    COMPUTE_2,
    COMPUTE_3,
    COMPUTE_NEXT_PLAYER_TURN_2,
    COMPUTE_NEXT_PLAYER_TURN_3,
    COMPUTE_WINNER,
    FINAL,

    NONE
}
